### ISSUE TITLE
Problème avec tri des matchings

### ISSUE THREAD

**Issue by jak78** [betagouv/francaisaletranger#82]
Une fois sur l'écran d'admin, une fois une demande sélectionnée, on essaie de trier les matchings en affichant la meilleure offre en premier.
Mais pourtant j'observe ceci :
<img width="1224" alt="Capture d’écran 2020-03-30 à 22 35 26" src="https://user-images.githubusercontent.com/351773/77963231-4d649e00-72dd-11ea-8d97-d7e7179c9d85.png">
La 1ère offre est celle qui a le moins de critères qui correspondent. Je m'attendais à l'inverse.
Peut-être est-ce dû à la façon dont le tri est implémenté dans `_id.vue`:
```javascript
              this.helpers = response.data.sort(function (a, b) {
                return a.distanceInMeters - b.distanceInMeters && b.scoring - a.scoring
              })
```
Ici les distances étant identiques, `a.distanceInMeters - b.distanceInMeters` renvoie zéro et donc la soustraction de scoring n'est pas évaluée et la fonction se contente de renvoyer zéro même si les scorings sont différents.

**Comment by jak78** [comment]
Qu'en penses-tu @XjulI1 ?

**Comment by XjulI1** [comment]
Ça doit venir du fait que la première condition du `&&` dans le `sort()` renvoie `0` et donc en JavaScript c'est interprété comme `false`.

**Comment by jja-octo** [comment]
Oui, c'est ce que je dis. Quel bon algo prendre ? Est-ce qu'on trie d'abord par distance puis score ? Est-ce qu'on intègre la distance dans le calcul du score par le back, et on trie seulement par score ?

**Comment by XjulI1** [comment]
Oups pardon je n'étais pas allé jusqu'à la fin de ton message. On peut intégrer la distance dans le scoring back effectivement comme ça on renvoie directement la liste triée et le front ne fait que l'afficher.
